### PR TITLE
Fix issues with newer versions of gtk

### PR DESCRIPTION
**Pull request by IvanMalison**

### CODE REVIEW

**Comment by CristianHenzel** [comment]
Hello,

if you could redo the pull request without the "Remove check for mouse button state" commit, I would gladly pull it.
That check is actually needed to prevent lots of entries into the history if the mouse button is held down for a long time while selecting text, so I'm not sure why you removed it. Or am I missing something?

**Comment by IvanMalison** [comment]
@CristianHenzel In gtk3, those calls are deprecated and produce a ton of output. I don't often select for longer than a second so I didn't really mind this, but I can revert that last change if you would prefer. They should really be changed to using the device interface though.

**Comment by CristianHenzel** [comment]
Yes, please revert that change.

**Comment by IvanMalison** [comment]
@CristianHenzel change reverted. Merge?

**Pull request closed without merging**
