### PR TITLE
Allow users to select menu entry by prefix.

### PR DESCRIPTION
**Pull request by facetoe**
This commit allows users to just start typing after opening the menu and ClipIt will match menu entries based on the entered input.

### CODE REVIEW

**Comment by facetoe** [comment]
@CristianHenzel, any reason this has not been merged?

I'm not a C programmer usually, happy to fix anything that is out of place...

**Comment by astrapi69** [comment]
Yes this would be a cool Feature

**Comment by CristianHenzel** [comment]
Hello,


I meant to get back to this but somehow forgot to, sorry about that.
The only reason why I didn't test this yet, was that I don't really like having functional changes and cosmetic code changes in the same commits. If you could recreate it without the spacing changes (e.g. lines 457-528) I would be happy to test and then merge it immediately. If you really want to, you can also include the spacing changes, but in a separate commit, I wouldn't mind that.
Thanks a lot for your contribution!

- Cristian

**Comment by facetoe** [comment]
Not a problem! I should be able to get to this sometime next week.

**Comment by facetoe** [comment]
Hi @CristianHenzel, I've removed the cosmetic changes, should be good to test now.

**Pull request merged**
