### PR TITLE
Improve input matching feature.

### PR DESCRIPTION
**Pull request by facetoe**
Underline matched text and grey out non matching entries. Now matches input anywhere in the text.

### CODE REVIEW

**Comment by Epskampie** [comment]
I tested this functionality, and it's great! Really makes "finding as you type" in recent history a lot more visually clear.

One suggestion though: 
* As soon as you start typing the first match should be selected. Right now it waits until there is only 1 match, but sometimes the first one is already correct, and I just want to paste it without having to press down.
* If you keep typing, if the currently selected items doesn't match anymore, it should once again select the first match.

**Comment by facetoe** [comment]
Yep, both suggestions sound good. I'll have a go at implementing this when I get the chance.

**Comment by facetoe** [comment]
@Epskampie, I've implemented your suggestions.

**Comment by Epskampie** [comment]
Awesome, tested and works great! Hopefully a maintainer will merge soon, but in the meantime I'm already enjoying this version. :-)

**Comment by facetoe** [comment]
Excellent :) @CristianHenzel pops in on occasion and merges PRs.

**Pull request merged**
